/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.html",
    "./src/**/*.{html,js}",
    "./main.js",
  ],

  darkMode: "class",

  theme: {
    extend: {
      colors: {
        "error":                        "#ba1a1a",
        "surface":                      "#f9f9fc",
        "on-tertiary":                  "#ffffff",
        "on-tertiary-container":        "#ffe3b7",
        "secondary-container":          "#dae1e2",
        "tertiary-container":           "#886000",
        "on-secondary":                 "#ffffff",
        "primary-fixed-dim":            "#80d3e4",
        "on-secondary-fixed-variant":   "#414849",
        "surface-dim":                  "#dadadc",
        "on-primary-fixed":             "#001f25",
        "error-container":              "#ffdad6",
        "background":                   "#f9f9fc",
        "secondary-fixed":              "#dde4e5",
        "surface-container-low":        "#f3f3f6",
        "primary":                      "#005864",
        "on-secondary-fixed":           "#161d1e",
        "on-primary-container":         "#b1f1ff",
        "tertiary-fixed-dim":           "#ffba20",
        "on-primary-fixed-variant":     "#004e59",
        "on-tertiary-fixed-variant":    "#5e4200",
        "inverse-on-surface":           "#f0f0f3",
        "secondary":                    "#586061",
        "tertiary":                     "#694a00",
        "on-secondary-container":       "#5d6465",
        "surface-container":            "#eeeef0",
        "surface-bright":               "#f9f9fc",
        "tertiary-fixed":               "#ffdea8",
        "surface-tint":                 "#006876",
        "on-primary":                   "#ffffff",
        "on-background":                "#1a1c1e",
        "primary-container":            "#017281",
        "secondary-fixed-dim":          "#c1c8c9",
        "surface-container-lowest":     "#ffffff",
        "outline-variant":              "#bec8cb",
        "inverse-primary":              "#80d3e4",
        "on-error-container":           "#93000a",
        "primary-fixed":                "#a0efff",
        "on-surface-variant":           "#3e484b",
        "on-tertiary-fixed":            "#271900",
        "on-surface":                   "#1a1c1e",
        "surface-variant":              "#e2e2e5",
        "surface-container-high":       "#e8e8ea",
        "outline":                      "#6e797b",
        "on-error":                     "#ffffff",
        "surface-container-highest":    "#e2e2e5",
        "inverse-surface":              "#2f3133",
      },

      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },

      spacing: {
        "margin-desktop":   "64px",
        "margin-mobile":    "20px",
        "section-gap":      "80px",
        "container-max":    "1280px",
        "gutter":           "24px",
        "base":             "8px",
      },

      fontFamily: {
        "headline-lg":        ["Montserrat"],
        "headline-md":        ["Montserrat"],
        "headline-lg-mobile": ["Montserrat"],
        "label-sm":           ["Inter"],
        "label-md":           ["Inter"],
        "body-md":            ["Inter"],
        "display-lg":         ["Montserrat"],
        "body-lg":            ["Inter"],
      },

      fontSize: {
        "headline-lg":        ["32px", { lineHeight: "40px",  fontWeight: "600" }],
        "headline-md":        ["24px", { lineHeight: "32px",  fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px",  fontWeight: "600" }],
        "label-sm":           ["12px", { lineHeight: "16px",  letterSpacing: "0.05em",  fontWeight: "600" }],
        "label-md":           ["14px", { lineHeight: "20px",  letterSpacing: "0.01em",  fontWeight: "500" }],
        "body-md":            ["16px", { lineHeight: "24px",  fontWeight: "400" }],
        "display-lg":         ["48px", { lineHeight: "56px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg":            ["18px", { lineHeight: "28px",  fontWeight: "400" }],
      },
    },
  },

  plugins: [],
};
